type: taskWorkflow
actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
calculateCp: false
calendar:
cpDuration:
cpDurationUnit: Minutes
criticalEndpoints: []
customChoiceField1:
  label:
  value:
customField1:
  label:
  value:
customField2:
  label:
  value:
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration:
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.9.2.0
exportTable: ops_task_workflow
firstRun: ''
holdResources: false
instanceWait: -- None --
instanceWaitLookup: Task
lastRun: ''
layoutOption: -- None --
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration:
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
name: GL-010-Move-Extracts-SCD-INT-GL-ACCOUNTS-To-Local-WF-
notes:
- sysId: e6cc79aa23394282aad059ce65abdb7c
  text: |-
    <Object typeid="Reference">
        <ID>9789074</ID>
        <RID>5</RID>
        <ClassID>39</ClassID>
        <Label>GL-010-Move-Extracts-SCD-INT-GL-ACCOUNTS-To-Local</Label>
        <Name>GL-010-Move-Extracts-SCD-INT-GL-ACCOUNTS-To-Local</Name>
        <PID typeid="ObjectID">
            <ID>9789073</ID>
        </PID>
        <Enabled>0</Enabled>
        <GlobalDisable>0</GlobalDisable>
        <Visibility>127</Visibility>
        <Owner>LM\n1552454</Owner>
        <Flags>8</Flags>
        <Status>1</Status>
        <OperationDateTime>0001-01-01T00:00:00</OperationDateTime>
        <LockIsExclusive>0</LockIsExclusive>
        <LockMode>0</LockMode>
        <LockOperation>0</LockOperation>
        <LockOwner/>
        <LockFlags/>
        <Guid>b2106d67-c363-4748-81f2-ee7427c9e47c</Guid>
        <Client/>
        <Creator>LM\n1552454</Creator>
        <CreationTime>2025-01-24T20:22:13</CreationTime>
        <Description>(Update for Enhanced Data Encryption).</Description>
        <ReadOnly>0</ReadOnly>
        <RevisionAuthor>LM\a1536575</RevisionAuthor>
        <RevisionTime>2025-09-17T12:05:31</RevisionTime>
        <EventFilter>1966083;1966081;1966082;1966086;1966090;</EventFilter>
        <Documentation typeid="DocumentationProperties"/>
        <Properties typeid="VariableCollection">
            <Variable t="12" typeid="Variable">
                <Name>Extensions</Name>
                <Value typeid="VariableCollection">
                    <Variable t="12" typeid="Variable">
                        <Name>SLASettings</Name>
                        <Value typeid="VariableCollection"/>
                    </Variable>
                </Value>
            </Variable>
            <Variable t="1" typeid="Variable">
                <Name>$ImportedSymbols</Name>
                <Value/>
            </Variable>
            <Variable t="3" typeid="Variable">
                <Name>UseBusinessDaySemantics</Name>
                <Value>0</Value>
            </Variable>
            <Variable t="3" typeid="Variable">
                <Name>Preprocessing.Strict</Name>
                <Value>0</Value>
            </Variable>
            <Variable t="3" typeid="Variable">
                <Name>Preprocessing.InheritVariables</Name>
                <Value>0</Value>
            </Variable>
        </Properties>
        <Tags typeid="VariableCollection">
            <Variable t="12" typeid="Variable">
                <Name>V4_DateTimeEvent</Name>
                <Value typeid="DateTimeEvent">
                    <ID typeid="ObjectID">
                        <ID>9789078</ID>
                        <RID>3</RID>
                        <Label>DateTime</Label>
                        <Name>DateTime</Name>
                        <Path>/</Path>
                    </ID>
                    <PID typeid="ObjectID">
                        <ID>9789074</ID>
                        <RID>3</RID>
                        <ClassID>39</ClassID>
                        <Label>GL-010-Move-Extracts-SCD-F-TRN-INT-To-Local</Label>
                        <Name>GL-010-Move-Extracts-SCD-F-TRN-INT-To-Local</Name>
                        <Path>/PROD/SCD/Outbound/FCS/Plans/GL-INT-Move-Extracts-SCD-To-Local</Path>
                    </PID>
                    <Attached>1</Attached>
                    <Enabled>1</Enabled>
                    <EventID>1966083</EventID>
                    <Properties typeid="VariableCollection"/>
                    <Actions typeid="EventActionCollection">
                        <Count>1</Count>
                        <EventAction typeid="EventAction">
                            <CommandID>196609</CommandID>
                            <CommandArgument/>
                        </EventAction>
                    </Actions>
                    <V4Tag>0</V4Tag>
                    <Type>4</Type>
                    <DeferredUntil>2015-09-23T13:58:41</DeferredUntil>
                    <Interval>36000000000</Interval>
                    <IntervalOrigin>2020-06-16T17:00:36</IntervalOrigin>
                    <ComputeIntervalWithDelta>0</ComputeIntervalWithDelta>
                    <RunLastMissedExecution>1</RunLastMissedExecution>
                    <OnNonBusinessDayAction>3</OnNonBusinessDayAction>
                    <TimeZoneType>1</TimeZoneType>
                    <ConstraintProperties typeid="ConstraintSchedulingProperties">
                        <EarliestTimeEnabled>0</EarliestTimeEnabled>
                        <EarliestTime>1900-01-01T00:00:00</EarliestTime>
                        <LatestTimeEnabled>0</LatestTimeEnabled>
                        <LatestTime>1900-01-01T23:59:00</LatestTime>
                        <SpanBusinessDay>1</SpanBusinessDay>
                    </ConstraintProperties>
                </Value>
            </Variable>
            <Variable t="12" typeid="Variable">
                <Name>V4_Constraint</Name>
                <Value typeid="Constraint">
                    <PID typeid="ObjectID">
                        <ID>9789074</ID>
                        <RID>1</RID>
                        <ClassID>39</ClassID>
                        <Label>GL-010-Move-Extracts-SCD-F-TRN-INT-To-Local</Label>
                        <Name>GL-010-Move-Extracts-SCD-F-TRN-INT-To-Local</Name>
                        <Path>/</Path>
                    </PID>
                    <RID>2</RID>
                    <Expression/>
                    <FailureAction>1</FailureAction>
                    <RetryInterval>600000000</RetryInterval>
                    <RetryLimit>5</RetryLimit>
                    <V4WaitValues>290266774831360</V4WaitValues>
                    <Variables typeid="VariableCollection"/>
                </Value>
            </Variable>
            <Variable t="2" typeid="Variable">
                <Name>GrantedAccess</Name>
                <Value>-1</Value>
            </Variable>
        </Tags>
        <Variables typeid="VariableCollection"/>
        <SecurityAccounts typeid="SecurityAccountCollection">
            <Dirty>0</Dirty>
            <Count>2</Count>
            <SecurityAccount typeid="SecurityAccount">
                <Name>Authenticated Users</Name>
                <Permission>70</Permission>
                <PermissionType>1</PermissionType>
            </SecurityAccount>
            <SecurityAccount typeid="SecurityAccount">
                <Name>Administrators</Name>
                <Permission>-1</Permission>
                <PermissionType>1</PermissionType>
            </SecurityAccount>
        </SecurityAccounts>
        <Target typeid="ObjectID">
            <ID>1549507</ID>
        </Target>
        <SecurityDescriptor>AQAEgLwAAADYAAAAAAAAABQAAAACAKgAAgAAAAAAFABGAAAAAQEAAAAAAAULAAAAAAAYAP////8BAgAAAAAABSAAAAAgAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEUAVAAgAG8AcABlAHIAYQB0AGkAbwBuAC4AAAA7AgAAZQAAAGUAZQABBQAAAAAABRUAAACdQgFO7AIYamkrf0ZSdV4AAQIAAAAAAAUgAAAAIAIAAHMAYwBpAC4AQQBjAHQAaQB2AGUA</SecurityDescriptor>
        <TagNames typeid="TagCollection"/>
    </Object>
  title: Conversion Source
numberOfTasks: 1
opswiseGroups: []
overrideCalendar: false
overrideInstanceWait: "No"
resPriority: 10
resPriorityVar:
resolveNameImmediately: true
restrictionPeriod: None
restrictionPeriodAfterDate:
restrictionPeriodAfterTime:
restrictionPeriodBeforeDate:
restrictionPeriodBeforeTime:
restrictionPeriodDateList: []
retainSysIds: true
runCount: 0
runCriteria: []
runTime: 0
simulation: false
skippedOption: Show Skipped
startHeld: false
startHeldReason:
stepActions: []
stepConditions: []
summary: shell reference
sysId: 334a3ba50f434c0cabf9d9656029d15b
timeZonePref: -- System Default --
twDelayAmount:
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount:
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
userEstimatedDuration:
variables:
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: Extensions
  options: []
  required: false
  sysId: 6eead5b4dbe54c35b010fbaa444cfe9c
  value: SLASettings
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: Preprocessing_InheritVariables
  options: []
  required: false
  sysId: 2ff46f01e9dc44418394f82dc4108233
  value: '0'
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: Preprocessing_Strict
  options: []
  required: false
  sysId: e492b44689dc45a6860d46b7b92fde12
  value: '0'
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: UseBusinessDaySemantics
  options: []
  required: false
  sysId: a1e97dd998774a5a969efde43d8fe8ab
  value: '0'
version: 1
virtualResources: []
workflowEdges: []
workflowVertices:
- alias:
  conditionExpression:
  task:
    value: SCD-Download-Files-From-SFTP-To-Temp
  vertexId: '5000'
  vertexX: '241.5'
  vertexY: '89.0'
