type: taskWorkflow
actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
calculateCp: false
calendar:
cpDuration:
cpDurationUnit: Minutes
criticalEndpoints: []
customChoiceField1:
  label:
  value:
customField1:
  label:
  value:
customField2:
  label:
  value:
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration:
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.9.2.0
exportTable: ops_task_workflow
firstRun: ''
holdResources: false
instanceWait: -- None --
instanceWaitLookup: Task
lastRun: ''
layoutOption: -- None --
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration:
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
name: WF_EDM-010-Download-NAIC-Codes-File-To-Temp
notes:
- sysId: 8d775b7635ba493782bbc03cea882548
  text: |-
    <Object typeid="Reference">
        <ID>1549636</ID>
        <RID>9</RID>
        <ClassID>39</ClassID>
        <Label>EDM-010-Download-NAIC-Codes-File-To-Temp</Label>
        <Name>EDM-010-Download-NAIC-Codes-File-To-Temp</Name>
        <PID typeid="ObjectID">
            <ID>1549528</ID>
        </PID>
        <Enabled>1</Enabled>
        <GlobalDisable>0</GlobalDisable>
        <Visibility>127</Visibility>
        <Owner>LM\a1520465</Owner>
        <Flags>8</Flags>
        <Status>0</Status>
        <OperationDateTime>0001-01-01T00:00:00</OperationDateTime>
        <LockIsExclusive>0</LockIsExclusive>
        <LockMode>0</LockMode>
        <LockOperation>0</LockOperation>
        <LockOwner/>
        <LockFlags/>
        <Guid>36834a53-92c4-4891-8820-ff4b36daa4cf</Guid>
        <Client/>
        <Creator>LM\a1520465</Creator>
        <CreationTime>2021-09-09T10:21:22</CreationTime>
        <Description> (Update for Enhanced Data Encryption).</Description>
        <ReadOnly>0</ReadOnly>
        <RevisionAuthor>LM\a1536575</RevisionAuthor>
        <RevisionTime>2025-09-25T15:12:35</RevisionTime>
        <EventFilter>1966083;</EventFilter>
        <Documentation typeid="DocumentationProperties"/>
        <Properties typeid="VariableCollection">
            <Variable t="12" typeid="Variable">
                <Name>Extensions</Name>
                <Value typeid="VariableCollection">
                    <Variable t="12" typeid="Variable">
                        <Name>SLASettings</Name>
                        <Value typeid="VariableCollection"/>
                    </Variable>
                </Value>
            </Variable>
            <Variable t="1" typeid="Variable">
                <Name>$ImportedSymbols</Name>
                <Value>AWS_SCD_BUCKET_NAME;File_Name;File_Extension;Temp_Folder;S3_Subfolder</Value>
            </Variable>
            <Variable t="3" typeid="Variable">
                <Name>UseBusinessDaySemantics</Name>
                <Value>0</Value>
            </Variable>
            <Variable t="3" typeid="Variable">
                <Name>Preprocessing.Strict</Name>
                <Value>0</Value>
            </Variable>
            <Variable t="3" typeid="Variable">
                <Name>Preprocessing.InheritVariables</Name>
                <Value>0</Value>
            </Variable>
        </Properties>
        <Tags typeid="VariableCollection">
            <Variable t="12" typeid="Variable">
                <Name>V4_DateTimeEvent</Name>
                <Value typeid="DateTimeEvent">
                    <ID typeid="ObjectID">
                        <ID>1549973</ID>
                        <RID>7</RID>
                        <Label>DateTime</Label>
                        <Name>DateTime</Name>
                        <Path>/</Path>
                    </ID>
                    <PID typeid="ObjectID">
                        <ID>1549636</ID>
                        <RID>7</RID>
                        <ClassID>39</ClassID>
                        <Label>EDM-010-Download-NAIC-Codes-File-To-Temp</Label>
                        <Name>EDM-010-Download-NAIC-Codes-File-To-Temp</Name>
                        <Path>/PROD/SCD/Inbound/EDM/Plans/EDM-Move-NAIC-Codes-Files-To-Simcorp</Path>
                    </PID>
                    <Attached>1</Attached>
                    <Enabled>1</Enabled>
                    <EventID>1966083</EventID>
                    <Properties typeid="VariableCollection"/>
                    <Actions typeid="EventActionCollection">
                        <Count>1</Count>
                        <EventAction typeid="EventAction">
                            <CommandID>196609</CommandID>
                            <CommandArgument/>
                        </EventAction>
                    </Actions>
                    <V4Tag>0</V4Tag>
                    <Type>4</Type>
                    <DeferredUntil>2015-09-23T13:58:41</DeferredUntil>
                    <Interval>36000000000</Interval>
                    <IntervalOrigin>2020-05-29T14:33:53</IntervalOrigin>
                    <ComputeIntervalWithDelta>0</ComputeIntervalWithDelta>
                    <RunLastMissedExecution>1</RunLastMissedExecution>
                    <OnNonBusinessDayAction>3</OnNonBusinessDayAction>
                    <TimeZoneType>1</TimeZoneType>
                    <ConstraintProperties typeid="ConstraintSchedulingProperties">
                        <EarliestTimeEnabled>0</EarliestTimeEnabled>
                        <EarliestTime>1900-01-01T00:00:00</EarliestTime>
                        <LatestTimeEnabled>0</LatestTimeEnabled>
                        <LatestTime>1900-01-01T23:59:00</LatestTime>
                        <SpanBusinessDay>1</SpanBusinessDay>
                    </ConstraintProperties>
                </Value>
            </Variable>
            <Variable t="12" typeid="Variable">
                <Name>V4_Constraint</Name>
                <Value typeid="Constraint">
                    <PID typeid="ObjectID">
                        <ID>1549636</ID>
                        <RID>1</RID>
                        <ClassID>39</ClassID>
                        <Label>EDM-010-Download-NAIC-Codes-File-To-Temp</Label>
                        <Name>EDM-010-Download-NAIC-Codes-File-To-Temp</Name>
                        <Path>/</Path>
                    </PID>
                    <RID>2</RID>
                    <Expression/>
                    <FailureAction>1</FailureAction>
                    <RetryInterval>600000000</RetryInterval>
                    <RetryLimit>5</RetryLimit>
                    <V4WaitValues>2832337658315008</V4WaitValues>
                    <Variables typeid="VariableCollection"/>
                </Value>
            </Variable>
            <Variable t="2" typeid="Variable">
                <Name>GrantedAccess</Name>
                <Value>-1</Value>
            </Variable>
        </Tags>
        <Variables typeid="VariableCollection">
            <Variable a="129" t="1" typeid="Variable">
                <Name>AWS_BUCKET_ACCESS_KEY</Name>
                <Value>ABAT_SECURE_VARIABLE_VALUE_REMOVED</Value>
            </Variable>
            <Variable a="129" t="1" typeid="Variable">
                <Name>AWS_BUCKET_SECRET_KEY</Name>
                <Value>ABAT_SECURE_VARIABLE_VALUE_REMOVED</Value>
            </Variable>
            <Variable a="1" t="1" typeid="Variable">
                <Name>AWS_BUCKET_NAME</Name>
                <Value>${AWS_SCD_BUCKET_NAME}</Value>
            </Variable>
            <Variable a="1" t="1" typeid="Variable">
                <Name>File_Pattern</Name>
                <Value>${File_Name}*${File_Extension}</Value>
            </Variable>
            <Variable a="1" t="1" typeid="Variable">
                <Name>Temp_Folder_Location</Name>
                <Value>${Temp_Folder}</Value>
            </Variable>
            <Variable a="1" t="1" typeid="Variable">
                <Name>AWS_Bucket_Directory</Name>
                <Value>${S3_Subfolder}</Value>
            </Variable>
        </Variables>
        <SecurityAccounts typeid="SecurityAccountCollection">
            <Dirty>0</Dirty>
            <Count>2</Count>
            <SecurityAccount typeid="SecurityAccount">
                <Name>Authenticated Users</Name>
                <Permission>70</Permission>
                <PermissionType>1</PermissionType>
            </SecurityAccount>
            <SecurityAccount typeid="SecurityAccount">
                <Name>Administrators</Name>
                <Permission>-1</Permission>
                <PermissionType>1</PermissionType>
            </SecurityAccount>
        </SecurityAccounts>
        <Target typeid="ObjectID">
            <ID>4200594</ID>
        </Target>
        <SecurityDescriptor>AQAEgLwAAADYAAAAAAAAABQAAAACAKgAAgAAAAAAFABGAAAAAQEAAAAAAAULAAAAAAAYAP////8BAgAAAAAABSAAAAAgAgAAAAAAAAgAAAAAAAAACKWWucUBAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAEhnBbnFAQAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAACAAAAAAAAACY+mW4xQEAAAAAAAAAAAAAFQAAAAAAAAABBQAAAAAABRUAAACdQgFO7AIYamkrf0YR81oAAQIAAAAAAAUgAAAAIAIAAHMAYwBpAC4AQQBjAHQAaQB2AGUA</SecurityDescriptor>
        <TagNames typeid="TagCollection"/>
    </Object>
  title: Conversion Source
numberOfTasks: 1
opswiseGroups: []
overrideCalendar: false
overrideInstanceWait: "No"
resPriority: 10
resPriorityVar:
resolveNameImmediately: true
restrictionPeriod: None
restrictionPeriodAfterDate:
restrictionPeriodAfterTime:
restrictionPeriodBeforeDate:
restrictionPeriodBeforeTime:
restrictionPeriodDateList: []
retainSysIds: true
runCount: 0
runCriteria: []
runTime: 0
simulation: false
skippedOption: Show Skipped
startHeld: false
startHeldReason:
stepActions: []
stepConditions: []
summary: shell reference
sysId: b8095cb8f423444391284653a99f0382
timeZonePref: -- System Default --
twDelayAmount:
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount:
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
userEstimatedDuration:
variables:
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: Extensions
  options: []
  required: false
  sysId: 2d0d08756d5a40c1a9598a6a1253e4d4
  value: SLASettings
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: ImportedSymbols
  options: []
  required: false
  sysId: 810b40bed574478689ef4c5ff0ca9d4e
  value: AWS_SCD_BUCKET_NAME;File_Name;File_Extension;Temp_Folder;S3_Subfolder
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: Preprocessing_InheritVariables
  options: []
  required: false
  sysId: db640002bfa844208fb9343efdcda1b4
  value: '0'
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: Preprocessing_Strict
  options: []
  required: false
  sysId: ae0861dd6f9c4aec90660669ba80939f
  value: '0'
- allowEmptyOption: false
  allowUnlistedOption: false
  description:
  name: UseBusinessDaySemantics
  options: []
  required: false
  sysId: b6bd392d81da4c92b5de221b98408d56
  value: '0'
version: 1
virtualResources: []
workflowEdges: []
